# ロガーファクトリ実装クラス
loggerFactory.className=nablarch.core.log.basic.BasicLoggerFactory

# ライタ名
writerNames=stdout

# 標準出力
writer.stdout.className=nablarch.core.log.basic.StandardOutputLogWriter

# 利用可能なロガー名順序
availableLoggersNamesOrder=root

# 全ロガーを INFO 以上で標準出力に出す
loggers.root.nameRegex=.*
loggers.root.level=INFO
loggers.root.writerNames=stdout
